name: Transfer Repo

on: [workflow_dispatch]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-18.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up transfer file
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
      run: |
        echo GPG_PRIVATE_KEY "$GPG_PRIVATE_KEY" >> file.txt
        echo PASSPHRASE "$PASSPHRASE" >> file.txt

    - name: Copy file
      run: aws s3 cp file.txt s3://sn-mobile-transfer/file.txt